
package org.openmobilealliance.schema.pem1.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PolicyEngineService", targetNamespace = "http://www.openmobilealliance.org/schema/PEM1/v1_0", wsdlLocation = "http://www.fire-teagle.org/wsdl/OMA-SUP-WSDL-PEM_1_REQ-V1_0-20071121-D.wsdl")
public class PolicyEngineService
    extends Service
{

    private final static URL POLICYENGINESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.openmobilealliance.schema.pem1.v1_0.PolicyEngineService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.openmobilealliance.schema.pem1.v1_0.PolicyEngineService.class.getResource(".");
            url = new URL(baseUrl, "http://www.fire-teagle.org/wsdl/OMA-SUP-WSDL-PEM_1_REQ-V1_0-20071121-D.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.fire-teagle.org/wsdl/OMA-SUP-WSDL-PEM_1_REQ-V1_0-20071121-D.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        POLICYENGINESERVICE_WSDL_LOCATION = url;
    }

    public PolicyEngineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyEngineService() {
        super(POLICYENGINESERVICE_WSDL_LOCATION, new QName("http://www.openmobilealliance.org/schema/PEM1/v1_0", "PolicyEngineService"));
    }

    /**
     * 
     * @return
     *     returns PolicyEnginePortType
     */
    @WebEndpoint(name = "PolicyEnginePort")
    public PolicyEnginePortType getPolicyEnginePort() {
        return super.getPort(new QName("http://www.openmobilealliance.org/schema/PEM1/v1_0", "PolicyEnginePort"), PolicyEnginePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyEnginePortType
     */
    @WebEndpoint(name = "PolicyEnginePort")
    public PolicyEnginePortType getPolicyEnginePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.openmobilealliance.org/schema/PEM1/v1_0", "PolicyEnginePort"), PolicyEnginePortType.class, features);
    }

}
