//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:36 PM MEZ 
//


package oma.xml.fokus.pem1_input_template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import oma.xml.fokus.soap_pem1_input_template.FOKUSSOAPInputTemplateType;


/**
 * <p>Java class for FOKUSInputTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOKUSInputTemplateType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oma:xml:fokus:pem1-input-template}inputTemplateType">
 *       &lt;sequence>
 *         &lt;element name="requestMessage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="policyIdentifiers" type="{urn:oma:xml:fokus:pem1-input-template}policyIdentifiers" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOKUSInputTemplateType", propOrder = {
    "requestMessage",
    "policyIdentifiers"
})
@XmlSeeAlso({
    FOKUSSOAPInputTemplateType.class
})
public class FOKUSInputTemplateType
    extends InputTemplateType
{

    protected Boolean requestMessage;
    protected PolicyIdentifiers policyIdentifiers;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the requestMessage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestMessage() {
        return requestMessage;
    }

    /**
     * Sets the value of the requestMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestMessage(Boolean value) {
        this.requestMessage = value;
    }

    /**
     * Gets the value of the policyIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyIdentifiers }
     *     
     */
    public PolicyIdentifiers getPolicyIdentifiers() {
        return policyIdentifiers;
    }

    /**
     * Sets the value of the policyIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyIdentifiers }
     *     
     */
    public void setPolicyIdentifiers(PolicyIdentifiers value) {
        this.policyIdentifiers = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
