//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:36 PM MEZ 
//


package oma.xml.fokus.pem1_input_template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inputTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inputTemplateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="externalPolicyRulesTemplate" type="{urn:oma:xml:fokus:pem1-input-template}externalPolicyRulesTemplateType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="templateID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="templateVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inputTemplateType", propOrder = {
    "externalPolicyRulesTemplate"
})
@XmlSeeAlso({
    FOKUSInputTemplateType.class
})
public abstract class InputTemplateType {

    protected ExternalPolicyRulesTemplateType externalPolicyRulesTemplate;
    @XmlAttribute(name = "templateID", required = true)
    protected String templateID;
    @XmlAttribute(name = "templateVersion", required = true)
    protected String templateVersion;

    /**
     * Gets the value of the externalPolicyRulesTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalPolicyRulesTemplateType }
     *     
     */
    public ExternalPolicyRulesTemplateType getExternalPolicyRulesTemplate() {
        return externalPolicyRulesTemplate;
    }

    /**
     * Sets the value of the externalPolicyRulesTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalPolicyRulesTemplateType }
     *     
     */
    public void setExternalPolicyRulesTemplate(ExternalPolicyRulesTemplateType value) {
        this.externalPolicyRulesTemplate = value;
    }

    /**
     * Gets the value of the templateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateID() {
        return templateID;
    }

    /**
     * Sets the value of the templateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateID(String value) {
        this.templateID = value;
    }

    /**
     * Gets the value of the templateVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateVersion() {
        return templateVersion;
    }

    /**
     * Sets the value of the templateVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateVersion(String value) {
        this.templateVersion = value;
    }

}
