//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:36 PM MEZ 
//


package oma.xml.fokus.pem1_input_template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for policyIdentifiers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="policyIdentifiers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originatorID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="originatorIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="targetIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originatorApplicationID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="targetApplicationID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "policyIdentifiers", propOrder = {
    "originatorID",
    "originatorIDType",
    "targetID",
    "targetIDType",
    "originatorApplicationID",
    "targetApplicationID"
})
public class PolicyIdentifiers {

    @XmlSchemaType(name = "anyURI")
    protected String originatorID;
    protected String originatorIDType;
    @XmlSchemaType(name = "anyURI")
    protected List<String> targetID;
    protected String targetIDType;
    @XmlSchemaType(name = "anyURI")
    protected String originatorApplicationID;
    @XmlSchemaType(name = "anyURI")
    protected String targetApplicationID;

    /**
     * Gets the value of the originatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorID() {
        return originatorID;
    }

    /**
     * Sets the value of the originatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorID(String value) {
        this.originatorID = value;
    }

    /**
     * Gets the value of the originatorIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorIDType() {
        return originatorIDType;
    }

    /**
     * Sets the value of the originatorIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorIDType(String value) {
        this.originatorIDType = value;
    }

    /**
     * Gets the value of the targetID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTargetID() {
        if (targetID == null) {
            targetID = new ArrayList<String>();
        }
        return this.targetID;
    }

    /**
     * Gets the value of the targetIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetIDType() {
        return targetIDType;
    }

    /**
     * Sets the value of the targetIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetIDType(String value) {
        this.targetIDType = value;
    }

    /**
     * Gets the value of the originatorApplicationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorApplicationID() {
        return originatorApplicationID;
    }

    /**
     * Sets the value of the originatorApplicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorApplicationID(String value) {
        this.originatorApplicationID = value;
    }

    /**
     * Gets the value of the targetApplicationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetApplicationID() {
        return targetApplicationID;
    }

    /**
     * Sets the value of the targetApplicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetApplicationID(String value) {
        this.targetApplicationID = value;
    }

}
