//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:36 PM MEZ 
//


package oma.xml.fokus.soap_pem1_input_template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oma.xml.fokus.pem1_input_template.FOKUSInputTemplateType;


/**
 * <p>Java class for FOKUSSOAPInputTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOKUSSOAPInputTemplateType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oma:xml:fokus:pem1-input-template}FOKUSInputTemplateType">
 *       &lt;sequence>
 *         &lt;element name="event" type="{urn:oma:xml:fokus:soap-pem1-input-template}event"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOKUSSOAPInputTemplateType", propOrder = {
    "event"
})
public class FOKUSSOAPInputTemplateType
    extends FOKUSInputTemplateType
{

    @XmlElement(required = true)
    protected Event event;

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

}
