// Generated by Grails v1.2.1
package corerepository

import grails.test.*

class ResourceInstanceControllerTests extends ControllerUnitTestCase {
    protected void setUp() {
        super.setUp()
    }

    protected void tearDown() {
        super.tearDown()
    }

    void testSomething() {

    }
}
