//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:39 PM MEZ 
//


package oma.xml.fokus.pem1_output_template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enforcementAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enforcementAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="enforcementActionOperation" type="{urn:oma:xml:fokus:pem1-output-template}enforcementActionOperation" maxOccurs="unbounded"/>
 *         &lt;element name="enforcementActionDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enforcementAction", propOrder = {
    "enforcementActionOperation",
    "enforcementActionDescription"
})
public class EnforcementAction {

    protected List<EnforcementActionOperation> enforcementActionOperation;
    protected String enforcementActionDescription;
    @XmlAttribute(name = "id", required = true)
    protected int id;

    /**
     * Gets the value of the enforcementActionOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enforcementActionOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnforcementActionOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnforcementActionOperation }
     * 
     * 
     */
    public List<EnforcementActionOperation> getEnforcementActionOperation() {
        if (enforcementActionOperation == null) {
            enforcementActionOperation = new ArrayList<EnforcementActionOperation>();
        }
        return this.enforcementActionOperation;
    }

    /**
     * Gets the value of the enforcementActionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnforcementActionDescription() {
        return enforcementActionDescription;
    }

    /**
     * Sets the value of the enforcementActionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnforcementActionDescription(String value) {
        this.enforcementActionDescription = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
