//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:39 PM MEZ 
//


package oma.xml.fokus.pem1_output_template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FOKUSOutputTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOKUSOutputTemplateType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oma:xml:fokus:pem1-output-template}outputTemplateType">
 *       &lt;sequence>
 *         &lt;element name="enforcementData" type="{urn:oma:xml:fokus:pem1-output-template}enforcementData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOKUSOutputTemplateType", propOrder = {
    "enforcementData"
})
public class FOKUSOutputTemplateType
    extends OutputTemplateType
{

    protected EnforcementData enforcementData;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the enforcementData property.
     * 
     * @return
     *     possible object is
     *     {@link EnforcementData }
     *     
     */
    public EnforcementData getEnforcementData() {
        return enforcementData;
    }

    /**
     * Sets the value of the enforcementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnforcementData }
     *     
     */
    public void setEnforcementData(EnforcementData value) {
        this.enforcementData = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
