//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 03:01:39 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oma:xml:fokus:pem1-output-template")
package oma.xml.fokus.pem1_output_template;
